### PR TITLE
Improve service installation support for docker driver

### PR DESCRIPTION
**Pull request by rmg**
* [x] run strong-pm as `docker` group
  * minimal change, covers Upstart 1.4 and systemd
* [x] add strong-pm user to `docker` group
  * required to support Upstart 0.6 environments
* [x] detect docker and fail if not found

connect to strongloop-internal/scrum-nodeops#615
connect to strongloop-internal/scrum-nodeops#618

### CODE REVIEW

**Comment by rmg** [comment]
Found and fixed a bug in the docker driver with `env-unset` along the way.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@sam-github do you want me to rebase/squash this before you look at it?

**Comment by sam-github** [comment]
LGTM

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@sam-github had to make one more change to support 0.12/iojs, can you take one more pass at the latest commit to make sure I didn't do anything stupid?

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
