### PR TITLE
docker: use official node image as base

### PR DESCRIPTION
**Pull request by rmg**
nodesource/node has been deprecated and the replacement doesn't get
updated as quickly as the official image.

Also change the Dockerfile to pull strong-pm from npm instead of the
production branch of the strongloop/strong-pm repo.

### CODE REVIEW

**Comment by rmg** [comment]
The major downside to this is the official node image is a lot larger than the nodesource one.. but it is based on buildpack-deps, so it is far more likely that a user will have the majority of the image's layers already downloaded.

**Comment by kraman** [comment]
LGTM

**Comment by kraman** [comment]
On a side note, do you know what UID ends up being strong-pm?

**Comment by rmg** [comment]
1000

**Pull request merged**
