### PR TITLE
Use /var/lib/strong-pm instead of /var/lib/strong-pm/.strong-pm

### PR DESCRIPTION
**Pull request by rmg**
Change the default basedir in pm-install to something more practical. There is no reason to create the additional .strong-pm directory inside a dedicated strong-pm root directory.

Connected to strongloop-internal/scrum-nodeops#90

### CODE REVIEW

**Comment by rmg** [comment]
@sam-github I made all the changes at once, but then munged it into multiple commits in case it made review easier, so there may be syntax errors and the like in the individual commits that aren't present in the final result.

**Comment by sam-github** [comment]
@rmg you can run unit tests against each of the stages, if you'd like, to ensure tests pass.

**Comment by rmg** [comment]
@sam-github this is `slc pm-install`, not `slc pm`. This PR does not alter the behaviour of pm itself at all, only the generation of the init script.

**Comment by sam-github** [comment]
LGTM, then, sorry I wasn't paying more attention ;-)

**Comment by cgole** [comment]
verified

**Pull request merged**
