### PR TITLE
Replace env pmctl with mesh model based API

### PR DESCRIPTION
**Pull request by rmg**
Replaces `env-set` and `env-unset` with Service model methods provided by strongloop/strong-mesh-models#21 and replaces `env-get` with model instance access.

Based on #134 
Connected to #48

### CODE REVIEW

**Comment by sam-github** [comment]
LGTM

**Comment by rmg** [comment]
I think the vagrant and docker tests have caught a regression in `pmctl env-set`. I'm looking into it now. Hopefully not too long before this can be merged (possibly with re-review, depending on how complex the changes are).

**Comment by rmg** [comment]
@sam-github @kraman I've more or less completely rewritten this PR because I kept running into problems as I was finishing up the tests.

I'm re-assigning for a full review.

**Comment by sam-github** [comment]
LGTM

**Comment by sam-github** [comment]
@rmg this PR broke `npm run lint`!

**Pull request merged**
