### PR TITLE
server: report pm and API version at startup

### PR DESCRIPTION
**Pull request by sam-github**
Should help in trouble-shooting issues like #158

### CODE REVIEW

**Comment by kraman** [comment]
Good idea. LGTM

**Comment by rmg** [comment]
:+1: LGTM

**Comment by rmg** [comment]
We should also at something to strong-mesh-models so that PM or other implementers can report their version as part of their status.

**Comment by sam-github** [comment]
@rmg I report the strong-mesh-models version in this PR as the API version, its easy to get: `require('strong-mesh-models/package.json').version`. Technially, that's not "exactly" the API version... we could make a breaking change to the js API of mesh models that doesn't effect the API, but its a good start.

**Comment by rmg** [comment]
@sam-github I meant the version reported by the API itself when you make a status call. As in add it to `lib/ctl.js:99` so it is part of the output of `slc ctl status`.

**Pull request merged**
