### PR TITLE
wip, spawn npm on windows

### PR DESCRIPTION
**Pull request by sam-github**
totally untested, but I'll be mucking around on windows soon, I'll test then if no one beats me to it

connected to #165

### CODE REVIEW

**Comment by sam-github** [comment]
@piscisaureus this is the best way, isn't it? It puts an intermediary shell between pm and npm, which makes it easier to leak processes on linux, but I suspect that cmd.exe might kill its children on windows.

Other approach would be to find "npm" in the path, and directly call node on it.

or just use https://www.npmjs.com/package/child_process2...

**Comment by piscisaureus** [comment]
@sam-github I can't tell whether this will work. There are subtle difficulties with quoting command line arguments on windows. But quite possibly these don't really happen with simple NPM commands, in which case this would work fine indeed.

I would suggest `cmd /s/c` btw.

**Comment by sam-github** [comment]
Thanks for suggestion on `/s/c`. In this case, there literally are only two commands we run, `npm install` and `npm rebuild`, so there are no weird quoting issues we need to avoid.

**Comment by piscisaureus** [comment]
Oh, ok in that case, lgtm :)

If we're ever going to run more complicated commands, we need to do better quoting, which is really weird and impossible on windows.

**Comment by piscisaureus** [comment]
@sam-github Can this be closed?

**Pull request closed without merging**
