### PR TITLE
Add HTTP auth support

### LINKED ISSUE #99: Add HTTP basic auth support
* allow setting a user:pass via `SL_PM_BASIC_AUTH` environment variable
 * allow setting a user:pass on `slc pm`/`sl-pm` command line
   * if set, overrides `SL_PM_BASIC_AUTH` value
 * allow setting a user:pass during `slc pm-install`/`sl-pm-install`
   * sets `SL_PM_BASIC_AUTH` environment variable in OS service file

Continuation of #40

### PR DESCRIPTION
**Pull request by rmg**
Depends on:
 * release of strong-fork-pushover that includes https://github.com/strongloop-forks/strong-fork-pushover/commit/6d673fbc4f86112e9ca33bf56cacd1083ee364b7
 * https://github.com/strongloop/strong-remoting/pull/163

TODO:
 * ~~add support for Digest auth requests to `pmctl` for downloading snapshots (`http.get` doesn't cut it, probably need something like `request`)~~
 * [x] Add comments about the state of Digest auth support in the code and document it as unsupported in the usage text.
 * [x] Add CLI options for setting `SL_PM_AUTH` during `sl-pm-install`

Closes #99

### CODE REVIEW

**Comment by rmg** [comment]
@sam-github I've added pm-install support, rebased, and cleaned it up. PTAL.

**Comment by sam-github** [comment]
Code looks great, some suggestions on the docs.

**Comment by rmg** [comment]
@sam-github I've extended the usage docs for `pm` and `pmctl` and squashed everything into a ready to merge state. Did you want to give the usage text a once over? Or shall I just merge as is?

**Comment by sam-github** [comment]
LGTM

**Comment by cgole** [comment]
verified.

**Pull request merged**
