### PR TITLE
Cleanup trace enablement

### PR DESCRIPTION
**Pull request by sam-github**
connected to strongloop-internal/scrum-nodeops#937

### CODE REVIEW

**Comment by sam-github** [comment]
something wrong with strong-debugger on amazon-4, but otherwise good.

**Comment by kraman** [comment]
:+1:

**Comment by sam-github** [comment]
re: amazon-4 test failure.

Early on, I see evidence strong-debugger was installed:

```
/mnt/jenkins/workspace/strong-pm/3c21596a/node_modules/strong-runner/node_modules/strong-supervisor/node_modules/strong-debugger/build
...    
strong-runner@5.0.7 node_modules/strong-runner                                   
└── strong-supervisor@3.2.8 (async@1.4.2, ... strong-debugger@1.0.6)
```

Then this, during preparation:

```
2015-09-29T23:47:47.945559247Z   strong-pm:prepare dir "/home/strongloop/.strong-pm/svc/1/work/6941373fbf00bd16e08632f407ea1cf718e55d3a.1443570467051": `npm rebuild` => OK +832ms
2015-09-29T23:47:47.945915454Z   strong-pm:prepare dir "/home/strongloop/.strong-pm/svc/1/work/6941373fbf00bd16e08632f407ea1cf718e55d3a.1443570467051": `"npm install --production"`... +0ms
2015-09-29T23:47:48.274247651Z npm info it worked if it ends with ok
2015-09-29T23:47:48.275024742Z npm info using npm@2.14.4
2015-09-29T23:47:48.275403333Z npm info using node@v4.1.1
2015-09-29T23:47:48.666165716Z npm info preinstall test-app@0.0.0
2015-09-29T23:47:48.702297562Z npm info build /home/strongloop/.strong-pm/svc/1/work/6941373fbf00bd16e08632f407ea1cf718e55d3a.1443570467051
2015-09-29T23:47:48.708978215Z npm info linkStuff test-app@0.0.0
2015-09-29T23:47:48.715623547Z npm info install test-app@0.0.0
2015-09-29T23:47:48.716747625Z npm info postinstall test-app@0.0.0
2015-09-29T23:47:48.731562944Z npm info ok 
2015-09-29T23:47:48.740672165Z   strong-pm:prepare dir "/home/strongloop/.strong-pm/svc/1/work/6941373fbf00bd16e08632f407ea1cf718e55d3a.1443570467051": `npm install --production` => OK +792ms
2015-09-29T23:47:48.740672165Z   strong-pm:direct:container:1 onCommit prepared, err? undefined +0ms
2015-09-29T23:47:48.740672165Z   strong-pm:direct:container:1 on prepared: 1/deploy/master +1ms
2015-09-29T23:47:48.740672165Z Run request for commit "1/deploy/master" on current (none)
2015-09-29T23:47:48.740672165Z Start Runner: commit 1/deploy/master
2015-09-29T23:47:49.063939262Z module.js:338
2015-09-29T23:47:49.063939262Z     throw err;
2015-09-29T23:47:49.063939262Z     ^
2015-09-29T23:47:49.063939262Z 
2015-09-29T23:47:49.063939262Z Error: Cannot find module 'strong-debugger/package.json'
2015-09-29T23:47:49.063939262Z     at Function.Module._resolveFilename (module.js:336:15)
2015-09-29T23:47:49.063939262Z     at Function.Module._load (module.js:286:25)
2015-09-29T23:47:49.063939262Z     at Module.require (module.js:365:17)
2015-09-29T23:47:49.063939262Z     at require (module.js:384:17)
2015-09-29T23:47:49.063939262Z     at Object.<anonymous> (/usr/local/lib/node_modules/strong-pm/node_modules/strong-runner/node_modules/strong-supervisor/lib/runctl.js:4:23)
...
2015-09-29T23:47:49.068151322Z Unexpected exit with 1 from Runner: commit 1/deploy/master
2015-09-29T23:47:50.070571168Z Start Runner: commit 1/deploy/master
2015-09-29T23:47:50.372266601Z module.js:338
2015-09-29T23:47:50.372266601Z     throw err;
```

But something is odd there, at this point, it appears the the strong-pm being run in is in `/usr/local/lib/...`, when it should be in `/mnt/jenkins/workspace/strong-pm/3c21596a/`.

@rmg, comment? Is `amazon-4` different in some way? Or... could it be that the PATH is not correct, and sl-pm is somehow running from a global install?

**Comment by rmg** [comment]
Based on the path, `/home/strongloop/` I'm inclined to think this is happening _inside_ a docker container - there is no `strongloop` user on any of our test VMs.

**Comment by sam-github** [comment]
I will merge, the failures are not related.

**Pull request merged**
