### PR TITLE
Make minkelite optional

### PR DESCRIPTION
**Pull request by kraman**

### CODE REVIEW

**Comment by sam-github** [comment]
LGTM

**Comment by curtisr7** [comment]
@kraman -- Do we really care to make minkelite configurable? We could simplify the code if we remove the configurable bits and make it an all or nothing proposition... If the dependency isn't able to load, log a message and life goes on.

**Comment by Setogit** [comment]
To mitigate the binary dependency issue, either what's implemented in this PR or what @curtisr7 suggested seems good (no big preference).  I'm leaning a bit toward separating tracing completely (not only minkelite but tracing itself).  But again, for the binary dependency removal, since @kraman has it, why not just take it.

**Comment by curtisr7** [comment]
LGTM

**Pull request merged**
