### PR TITLE
Allow PM to be run with env and IDs specified by Executor

### PR DESCRIPTION
**Pull request by kraman**

### CODE REVIEW

**Comment by kraman** [comment]
Depends on https://github.com/strongloop/strong-mesh-models/pull/11

**Comment by kraman** [comment]
Tests will fail till mesh-models are merged in

**Comment by sam-github** [comment]
LGTM, but the package dep spec on mesh models needs updating to `^4`, c.f. https://github.com/strongloop/strong-mesh-models/pull/11#issuecomment-69095566

**Comment by sam-github** [comment]
And maybe the major version needs a bump, too, since its not backwards compat. That would allow us to publish strong-pm, and arc to update to the latest at their convenience. Unless the remote deploy and metrics doesn't work... at which point API versioning starts to sound important.

Maybe we need to expose the package version via the REST API, so that clients can bail early if they don't support the API version they are interacting with?

**Comment by rmg** [comment]
For exposing versions, if it makes sense to version the API separately from the package we can do so by adding something like `"api_version": "x.y.x"` to package.json. Though I suppose that raises the question of whether the API could/should be expressed as a module that could internally support multiple versions for backwards compatibility.

**Comment by sam-github** [comment]
the strong-mesh-model package.version might be worth putting into the rest api as `/api/version`. its potentially possible we make the REST api incompatible but NOT change the models, but I'm hard pressed to think of how.

**Comment by kraman** [comment]
Rebased on master

**Pull request merged**
