### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by sam-github**
connected to strongloop-internal/scrum-nodeops#775

### CODE REVIEW

**Comment by rmg** [comment]
LGTM. 

And on the topic of `t.end()`, the methods on tap.Test are prebound as of tap@1.3.0, so we can now do things like `server.close(t.end);` :-)

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
cool to know about t.end, thanks. No idea why all the tests are failing. argh.

**Comment by sam-github** [comment]
OK, I see, tests won't pass because of control-channel, I'm going to merge, master is no more broken with this than it was before.

**Pull request merged**
