### PR TITLE
Allow PM to be run with env and IDs specified by Executor

### PR DESCRIPTION
**Pull request by kraman**
Connect to strongloop-internal/scrum-nodeops#123

### CODE REVIEW

**Comment by kraman** [comment]
This PR is reapplying commits that were reverted earlier

**Comment by rmg** [comment]
If this was already applied once, does it need to be reviewed again? Also:
 * merge conflicts
 * we need to decide what to do about breaking changes without blocking maintenance

**Comment by rmg** [comment]
Blocked on strongloop/strong-tools#24.

**Comment by kraman** [comment]
Rebased onto master

**Comment by rmg** [comment]
strongloop/strong-tools#24 has been fixed. It should be safe to increment the major version without breaking staging releases from other branches.

**Comment by kraman** [comment]
Missed a commit. Added above.

**Pull request closed without merging**
