### PR TITLE
WIP: Integrate gateway

### PR DESCRIPTION
**Pull request by kraman**
Connected to strongloop/strong-scheduler#14

Replaces https://github.com/strongloop/strong-pm/pull/114

### CODE REVIEW

**Comment by kraman** [comment]
@slnode test please

**Comment by kraman** [comment]
Depends on strongloop/strong-mesh-models#16

**Comment by sam-github** [comment]
Looks good, but I'm nervous about merging. I think we all need to come to a better understanding about the flow for breaking changes.

How does this effect arc? Does the arc "start internal with one worker" feature need tweaking, or will it work as-is, even though "cpus" was renamed?

**Comment by sam-github** [comment]
By flow, I mean flow of PRs into branches, and upstream deps, etc. In case that wasn't clear.

**Pull request merged**
