### PR TITLE
Support directly installable CLIs

### PR DESCRIPTION
**Pull request by sam-github**
/to @rmg @crandmck

### CODE REVIEW

**Comment by rmg** [comment]
I like dropping the `slpm` and `slpmctl`, but I have a strong preference for **not** adding the variants without the `sl-` prefix.

FYI, removing commands will result in orphaned symlinks in users' path when they upgrade or install over top of existing versions because npm doesn't run any sort of uninstall in these cases. For that reason I try to keep bin lists as short as possible and as static as possible across releases.

**Comment by crandmck** [comment]
So, if I understand correctly, on a "standalone" PM install, the commands will be `pm` (vs. `slc pm`) and `pm-install` (vs. `slc pm-install`).  And I think the consensus is NOT to document `ctl` command (vs. `slc ctl`) since there is not a realistic use case.  Right?

/cc @DeniseLee

**Comment by rmg** [comment]
@sam-github you assigned back to me without responding to my feedback.

**Comment by sam-github** [comment]
> a strong preference for not adding the variants without the sl- prefix

why? you like the long names?

**Comment by rmg** [comment]
> > a strong preference for not adding the variants without the sl- prefix

> why? you like the long names?

I was opposed to the original `slpm` aliasing when it went in, and this is just changing the aliases.

 1. namespacing
 2. branding
 3. $PATH pollution
 4. pm/pmctl look more like power management

**Comment by sam-github** [comment]
ok, sounds reasonable to me.

**Pull request closed without merging**
