### PR TITLE
Use a named file minkelite.db with overwrite option.

### PR DESCRIPTION
**Pull request by Setogit**
connect to strongloop-internal/scrum-nodeops#869

### CODE REVIEW

**Comment by Setogit** [comment]
@slnode test please

**Comment by kraman** [comment]
:+1:

**Comment by Setogit** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by Setogit** [comment]
hmm, i'm hesitant about merging because my local test n OSX fails with both master and this branch.  same failure:

```
./test/test-install-systemd.sh ........................ 7/8
  not ok # exit 1 should be 0: 'node ../bin/sl-pm-install.js --port 7777 --job-file /var/folders/fr/n8lr0rq555l1r3b6v69ckb5h0000gn/T/sl-svc-installXXXXXX.ovXupoD7/systemd-with-docker.service --user seto --base /var/folders/fr/n8lr0rq555l1r3b6v69ckb5h0000gn/T/sl-svc-installXXXXXX.ovXupoD7/deeply/nested/sl-pm --driver docker --systemd'

Bail out! # # exit 1 should be 0: 'node ../bin/sl-pm-install.js --port 7777 --job-file /var/folders/fr/n8lr0rq555l1r3b6v69ckb5h0000gn/T/sl-svc-installXXXXXX.ovXupoD7/systemd-with-docker.service --user seto --base /var/folders/fr/n8lr0rq555l1r3b6v69ckb5h0000gn/T/sl-svc-installXXXXXX.ovXupoD7/deeply/nested/sl-pm --driver docker --systemd'

```

**Comment by Setogit** [comment]
The test failure on my local OSX turned out to be caused by docker being not installed while executing test-install-systemd.sh and test-install.sh. In the CI environment, dockers is available.

Merging to the master.

**Pull request merged**
