### PR TITLE
test: update expectations for persisted set-size

### PR DESCRIPTION
**Pull request by sam-github**
Other half of https://github.com/strongloop/strong-mesh-models/pull/46, which doesn't effect pm itself, but does effect its tests.

connected to strongloop-internal/scrum-nodeops#703

### CODE REVIEW

**Comment by sam-github** [comment]
@rmg waiting for green on this, to make sure that base pm is working well, then I'll rebase #232 onto this once it hits master.

**Comment by sam-github** [comment]
they are all failing on test-server-metadata, that's promising, I should be able to repro locally.

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@sam-github PTAL.

Failure on CI seems to be a port conflict.. wait for a rebuild? Merge as is?

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
Finally passed. Which means the test pass/fail is semi-random :-(

**Pull request merged**
