### PR TITLE
test: add wiggle room to pmctl log tests

### PR DESCRIPTION
**Pull request by rmg**
The goal is to reduce likelyhood of timing issues failing the tests
prematurely.

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
Example of timing issue failing a build: http://ci.strongloop.com/job/strong-pm/566

**Comment by sam-github** [comment]
LGTM

**Comment by rmg** [comment]
Rebased and fixed a couple style warnings.

**Pull request merged**
