### PR TITLE
Cleanup env API

### PR DESCRIPTION
**Pull request by rmg**
Fixes a small bug, extends tests, and fixes some lint warnings, all related to #138

### CODE REVIEW

**Comment by rmg** [comment]
Depends on strongloop/strong-mesh-models#27

**Comment by sam-github** [comment]
LGTM

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
Pushed one more commit to make the build pass.

@kraman can you take a look?

**Comment by sam-github** [comment]
LGTM

**Pull request merged**
