### PR TITLE
Pass description option when installing service.

### PR DESCRIPTION
**Pull request by braincomb**
When listing services, for example with `systemctl` - the default pre-set description "a node app" was not very descriptive. We should set the description to something more representing.

The following change will for example result in systemd output looking like this:

```shell
systemctl | grep strong
strong-pm.service     loaded active running   StrongLoop Process Manager
```
```shell
systemctl status | grep strong
strong-pm.service - StrongLoop Process Manager
   Loaded: loaded (/etc/systemd/system/strong-pm.service; enabled)
   CGroup: name=systemd:/system/strong-pm.service
```

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rmg** [comment]
@slnode ok to test

**Comment by rmg** [comment]
@braincomb can you add tests? The main one would be a one-liner in `test/test-install-systemd.sh`.

Might also look at `test/test-install-upstart-0.6.sh` and `test/test-install.sh` to verify the Upstart behaviour, but I don't recall for sure if that property translates to an actual config or just a comment there.

**Comment by braincomb** [comment]
@rmg I did look at the test files initially, but none of the options were tested to begin with so I didn't include any. How would a one-liner look like?

`assert_file $TMP/systemd.service "Description=StrongLoop Process Manager"`

**Comment by rmg** [comment]
@braincomb yep :-)

**Comment by rmg** [comment]
BTW, the reason for adding the test even though the other fields aren't all covered is because at least one user (you!) cares about this field enough to contribute, so we want to make sure it doesn't break in the future ;-)

**Comment by rmg** [comment]
Landed in f2e6e793196551d91e83b93ae4c1f0dd43aa3855

**Pull request closed without merging**
