### PR TITLE
Update Dockerfile to use latest node for base.

### PR DESCRIPTION
**Pull request by gausie**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by SemonCat** [comment]
+1

**Comment by rmg** [comment]
@gausie @SemonCat I'm really sorry I didn't notice this earlier.

I think `node:argon` or `node:4` would be more appropriate as the base for `strongloop/strong-pm:latest`. I'm going to see about setting up multiple tags so we can support different versions of node.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rmg** [comment]
@SemonCat @gausie I think you'll be happy with this: https://hub.docker.com/r/strongloop/strong-pm/tags/

I've split the repo into a separate tag for each major version of node.

**Pull request closed without merging**
