### PR TITLE
pm: startup log of base dir and pid

### PR DESCRIPTION
**Pull request by sam-github**
connected to strongloop-internal/scrum-nodeops#747

### CODE REVIEW

**Comment by rmg** [comment]
:+1: on intent, but it raises the question of whether this is something that should be handled by a logger.. I'm ok with punting on that conversation for another time, though.

LGTM

**Comment by rmg** [comment]
The failed test is a timeout because a test app is spinning with `EADDRINUSE`.. weird.

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
I don't know how long we'll get by without a logger, particularly one that is run-time configurable. I want to send a message got mesh/pm saying `slc ctl set-log-level INFO`. DEBUG has been getting us by so far, its really simple, and does almost enough.

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
Its hard to believe this could cause a test failure, but I'll keep poking it until it goes green.

**Comment by sam-github** [comment]
@rmg I poked master, we'll see if its green, this is a time suck. :-(

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Pull request merged**
