### PR TITLE
Multiapp support

### PR DESCRIPTION
**Pull request by sam-github**
refactor against strongloop/strong-runner#1

add multi-app support

connect to #141 

replaces #172, #175, #169

### CODE REVIEW

**Comment by kraman** [comment]
LGTM for PM implementation but would need to be split up differently for Mesh.
Most likely the same code will not be directly usable in the mesh but thats fine as we can evolve the 2 products together once multi-app PM is closer to complete.

**Comment by sam-github** [comment]
test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@sam-github CI is green, :shipit: !

**Pull request closed without merging**
