### PR TITLE
call acceptClient to open websocket channel

### PR DESCRIPTION
**Pull request by Setogit**
connect to strongloop-internal/scrum-nodeops#790

### CODE REVIEW

**Comment by rmg** [comment]
@Setogit I believe this is part of #256.

**Comment by Setogit** [comment]
@rmg is right.  It is part of #256.   Is the test change included in #256?

**Comment by rmg** [comment]
I imagine @sam-github will be fixing the tests as part of upgrading to the new WS api, yes.

**Comment by Setogit** [comment]
Closing this PR.

**Pull request closed without merging**
