### PR TITLE
Update tests for tap@1.3.4

### PR DESCRIPTION
**Pull request by rmg**
Fixes the failures that weren't fixed by strongloop/strong-mesh-models#103.

R=@kraman or @sam-github, whoever gets to it first :-)

### CODE REVIEW

**Comment by kraman** [comment]
@slnode test please

**Comment by kraman** [comment]
:+1: but waiting for tests results

**Comment by sam-github** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by sam-github** [comment]
LGTM when green

**Comment by rmg** [comment]
Only build failures are on iojs-3 which is blocked on mapbox/node-sqlite3#495 being merged and released.

**Pull request merged**
