### PR TITLE
Portable symlink

### PR DESCRIPTION
**Pull request by sam-github**
connected to strongloop-internal/scrum-nodeops#848
depends on https://github.com/strongloop/strong-runner/pull/16

### CODE REVIEW

**Comment by rmg** [comment]
Interestingly enough, the IP lookup change is actually compatible with boot2docker, since it will find the `vboxnetN` interface and address. Not sure about native docker, though, since `docker[0-3]` are specifically filtered out of the candidate list.

**Comment by sam-github** [comment]
blocked on strong-pm build failures, but PTAL, @rmg

**Comment by rmg** [comment]
Changes LGTM once we can get master green on CI.

**Comment by sam-github** [comment]
@slnode test please

**Comment by sam-github** [comment]
io.js v3.x is broken because of sqlite3, everything else is green, merging

**Pull request merged**
